### ISSUE TITLE
Bot Broken! (API Change)

### ISSUE THREAD

**Issue by lemoncoco1** [thomasasfk/clipsync#3]
Hiya, I think Twitch changed up their API. Which means the bot is out of action right now.

It hasn't posted a correct link in 2 weeks. 

Could you take a look at it when you have time?

**Comment by thomasasfk** [comment]
Oh thanks for mentioning I'll take a look this week-end

**Comment by thomasasfk** [comment]
The bot should be working again @lemoncoco1

**Comment by lemoncoco1** [comment]
Thanks for fixing this <3
